/*TASK-4*/
USE TechShop;
/*1. Write an SQL query to find out which customers have not placed any orders.*/

SELECT CONCAT(FIRSTNAME,' ',LASTNAME) AS CUSTOMER FROM CUSTOMERS WHERE CUSTOMERID NOT IN  (SELECT CUSTOMERID FROM Orders);

/*2. Write an SQL query to find the total number of products available for sale. */

select 
coalesce(ProductName,'TotalProducts')as ProductName , sum(QuantityInStock) as QuantityAvailable
from products,Inventory
where products.productID=Inventory.productID 
group by rollup (ProductName);

select sum(QuantityInStock) from inventory;


/*3. Write an SQL query to calculate the total revenue generated by TechShop. */
select sum(TotalAmount) AS TOTALREVENUE from Orders;

/*4. Write an SQL query to calculate the average quantity ordered for products in a specific category.
Allow users to input the category name as a parameter.*/
DECLARE @CATGORYNAME VARCHAR(20) = 'ELECTRONICS';
SELECT AVG(QUANTITY) FROM ORDERDETAILS WHERE PRODUCTID IN
(SELECT PRODUCTID FROM Products WHERE Category=@CATGORYNAME);


SELECT * FROM PRODUCTS;
SELECT AVG(qUANTITY) FROM ORDERDETAILS;
SELECT * FROM Orders;

/*5. Write an SQL query to calculate the total revenue generated by a specific customer. Allow users 
to input the customer ID as a parameter*/

DECLARE @CustomerID INT = 13
SELECT 
	SUM(TotalAmount) TotalRevenue 
FROM orders where CustomerID=@CustomerID;
/*6. Write an SQL query to find the customers who have placed the most orders. List their names
and the number of orders they've placed.*/
WITH OrderCount AS(
	SELECT 
		C.CustomerID,
		C.FirstName,
		C.LastName,
		COUNT(O.OrderID) NoOfOrders
	FROM Customers C
	JOIN Orders O ON O.CustomerID = C.CustomerID
	GROUP BY C.CustomerID, C.FirstName, C.LastName
)
SELECT FirstName, LastName, NoOfOrders FROM OrderCount
WHERE NoOfOrders = (SELECT MAX(NoOfOrders) FROM OrderCount);


/*7. Write an SQL query to find the most popular product category, which is the one with the highest
total quantity ordered across all orders*/

select top 1 ProductName,sum(Quantity) from orderdetails,products
where products.productid=orderdetails.ProductID
group by productName
order by sum(Quantity) desc;

/*8. Write an SQL query to find the customer who has spent the most money (highest total revenue)
on electronic gadgets. List their name and total spending*/

select top 1concat(c.Firstname,' ',c.lastname),sum(o.TotalAmount) as Moneyspent  from
customers c join orders o on c.CustomerId=o.CustomerId
join orderdetails od on od.orderId=o.orderID
join products p on p.ProductID=od.ProductID
group by c.firstname,c.lastname
order by Moneyspent desc;

/*9. Write an SQL query to calculate the average order value (total revenue divided by the number of
orders) for all customers.*/

select concat(c.firstname,' ',c.lastname) as customer,(sum(od.Quantity*p.price)/COUNT(O.OrderID)) as avgorder
from customers c left join Orders o on c.CustomerId=o.CustomerID
left join OrderDetails od on od.orderId=o.orderID
left join products p on p.ProductID=od.ProductID
group by c.firstname,c.lastname
ORDER BY avgorder DESC;

/*9. Write an SQL query to calculate the average order value (total revenue divided by the number of
orders) for all customers.*/WITH OrderValue AS(SELECT	O.CustomerID,	C.FirstName+' '+C.LastName AS CustomerName,	SUM(O.TotalAmount) AS TotalRevenue,	COUNT(O.OrderID) AS NoOfOrdersFROM Orders O RIGHT JOIN Customers C ON C.CustomerID = O.CustomerIDGROUP BY O.CustomerID, C.FirstName, C.LastName)SELECT 	OV.CustomerID, 	OV.CustomerName,	AVG(OV.TotalRevenue/OV.NoOfOrders) AS AvgOrderValueFROM OrderValue OVGROUP BY OV.CustomerID, OV.CustomerName;


/*10. Write an SQL query to find the total number of orders placed by each customer and list their
names along with the order count*/

select concat(c.firstname,' ',c.lastname) as customer,(COUNT(O.OrderID)) as totalorders
from customers c left join Orders o on c.CustomerId=o.CustomerID
left join OrderDetails od on od.orderId=o.orderID
left join products p on p.ProductID=od.ProductID
group by c.firstname,c.lastname
order by c.firstname,c.lastname ;